name: Deploy Quitanda via SFTP

on:
  push:
    branches: [main]

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          local_path: './*'
          remote_path: '/home/wwwleo/domains/leoaraujo.com/public_html/quitanda/'
          sftp_only: true
