name: Deploy Quitanda via SFTP

on:
  push:
    branches: [main]

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

            - name: Deploy via SFTP com SSH
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          port: 2222
          sftp_only: true
          local_path: './*'
          remote_path: '/public_html/quitanda/'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

